### ISSUE TITLE
When having a "#" in the path, no images are shown. 

### ISSUE THREAD

**Issue by JKawohl** [owncloud/files_mediaviewer#148]
Steps to reproduce: 

Create a folder in ownCloud: #myimages
Create a subfolder in that: 20191511
Add images to the folder 20191511
Then click on a foto:

Expected behavior:  The foto is displayed large in the screen
Actual behavior: The fot is not displayed in the app.

Annotations we could identify the root cause: thanks to @PVince81 

In the path there is an "#" (not sure if this applies to other special characters also) which seems to keep the app from loading the images correctly.

**Comment by PVince81** [comment]
@micbar for scheduling

we might want to extend our acceptance tests in general to contain hashes in URLs as there might be other locations in OC where the JS code has trouble with them @phil-davis

**Comment by taburineagle** [comment]
I have the same issue, only affecting videos - if browsing in a path with videos and pictures, several pictures *do* show correctly (at random), but videos don't load at all (they show with a play button, as if they've loaded successfully, but no video actually plays) - I was not sure if the issue was related to mediaviewer, or just due to the fact I was browsing the folder from an externally connected mount connected to ownCloud (and not one of the folders under /var/www/owncloud/data/.../ itself.)

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/issues/36430 I raised a separte issue for reviewing core tests more generally.

**Comment by felixheidecke** [comment]
This PR fixes the issue: https://github.com/owncloud/files_mediaviewer/pull/152
