### ISSUE TITLE
How to install my modified app on my owncloud

### ISSUE THREAD

**Issue by DarkNavrel** [owncloud/files_mediaviewer#247]
Hi everyone, I have some experience in React-Native and Javascript but I have never worked with VUE, my question may be stupid, but I really have no idea what the next step is. I modified the files_mediaviewer, with some changes and additions that I coded, but how can I compile everything and install it on my owncloud external server? I have the original mediaviewer installed and I verified that in his folder on the server (apps-external/files_mediaviewer) there are only 3 code files. How do I install the application that modified on my main server?

**Comment by DeepDiver1975** [comment]
Did you build the vuejs app yet? refs https://github.com/owncloud/files_mediaviewer#building

To create a release bundle for you production server use: make dist and move the tar.gz to your server and extract it.

In addition: feel free to submit a PR so that the whole community can benefit from your enhancements! ;-)

**Comment by DarkNavrel** [comment]
Hello DeepDiver, thanks for your reply! As soon as I have tested my modifications and verified that they are working properly, I will be happy to share, it is something about artificial intelligence.
