### ISSUE TITLE
Text and icon in file actions menu is missing

### ISSUE THREAD

**Issue by JammingBen** [owncloud/files_mediaviewer#337]
The action for opening a file in the mediaviewer is not translated, also the icon is missing in the file actions menu. Changing this would be nice for PR https://github.com/owncloud/core/pull/38132.

![image](https://user-images.githubusercontent.com/50302941/101911645-ed8afa80-3bc0-11eb-89d6-695b625adcb3.png)

**Comment by jnweiger** [comment]
## tested with 1.0.4RC1 in serve 10.6.0

Unconfirmed. The untranslated menu entry with the missing icon is now missing completely:

![image](https://user-images.githubusercontent.com/1108546/104794251-ab983a00-57a6-11eb-9e73-d613f3ffab7d.png)

**Comment by JammingBen** [comment]
@jnweiger That's right, it is the same behavior as it was before this fix. Displaying the default actions in the menu is scheduled for 10.7. So you would have to test this with the code changes from https://github.com/owncloud/core/pull/38132.

Clicking on the photo directly still opens the media viewer, right?

**Comment by pmaier1** [comment]
This should be tackled for the 10.7 release.

**Comment by JanAckermann** [comment]
This can be taggled right now, due the required changes doesn't break anything at the core

**Comment by JammingBen** [comment]
Honestly, I don't know what still needs to be qualified or done here. The change has already been released with 1.0.4 a few days ago.

**Comment by jnweiger** [comment]
Seen in files_media_viewer 1.0.5-rc1

![image](https://user-images.githubusercontent.com/1108546/141096700-dfdc286f-dc18-4ca5-b940-3759e1d283da.png)

the english string is there, the icon is there.
But translations (here German) don't seem to work.

**Comment by jnweiger** [comment]
On a fresh test system, where 
* files_media_viewer-1.5.0-rc1 is installed in /var/www/owncloud/custom (due to docker)
* files_media_viewer-1.4.0 is installed in /var/www/owncloud/apps (complete bundle)

Firefox network console shows a mixture of js files from both folders:

![image](https://user-images.githubusercontent.com/1108546/141148512-bb5edd2f-2414-4dbb-b793-46fef510e0ff.png)

The `GET /apps/files_mediaviewer/l10n/de.js?v=01c457801b9747723dbfb198100dcf16 HTTP/1.1`
request is done without referer header.

**Comment by JanAckermann** [comment]
Not an files_mediaviewer issue, see:
https://github.com/owncloud/core/pull/39482
