### ISSUE TITLE
Port to Phoenix

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/files_mediaviewer#80]
An estimate on a Phoenix port it too early @ this stage. Keep this open as long as necessary.

**Comment by PVince81** [comment]
@felixheidecke what information is missing ? is the data model of the Phoenix files app not set in stone yet ? or is it the dynamic app loading issue ?

would be good to know what clarifications are needed to be able to provide estimates

**Comment by DeepDiver1975** [comment]
Phoenix is using a different tech basis:
- owncloud-sdk with Bearer token vs throwing plain paths to image and video tags using OC.filePath etc
- owncloud-design-system vs plain html + uikit + owncloud styles
- getText vs owncloud legacy translations
- webpack vs grunt/browserify

The basic vue components can be copied over but then require massive rework and adoption.

Estimate for this is: 1 week

**Comment by DeepDiver1975** [comment]
We can schedule this for the next phoenix sprint.

**Comment by PVince81** [comment]
so from my understanding, we still need need to do research about how to best loading previews/thumbnails with bearer token ?

after talking to @DeepDiver1975 at least two approaches would be possible:

1) Using JS data streams (blob stream?) to load the pictures with XHR into a "data:" style URL and plug this into image object.
    - pro: would likely work with current server setup
    - con: more convoluted as it needs the data streaming logic and need to make sure it's not storing the whole picture in memory

or

2) Use a temporary token that can be appended to the image URLs so we can use "img" tag directly. This would require new endpoints on the server.
    - pro: once the token is generated, it's straightforward: just a matter or rendering the "img" tags with the correct URL.
    - con: requires new endpoint on server that accept the token
    - con: might need yet another endpoint to generate said token ?

This is necessary because "img" tags only support loading images using the "src" attribute but don't support passing headers like "Bearer" token.

**Comment by DeepDiver1975** [comment]
Assigning myself and added to next sprint in order to get the backend api stuff sorted

**Comment by DeepDiver1975** [comment]
we might want to look into this mechanism: https://www.npmjs.com/package/vue-auth-image

**Comment by DeepDiver1975** [comment]
unassigning - this is being worked on ....

**Comment by felixheidecke** [comment]
Closed by https://github.com/owncloud/phoenix/pull/1530
